In [3]:
from google.colab import files
                                             #Use COlab
uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving irisDataset.csv to irisDataset.csv
User uploaded file "irisDataset.csv" with length 4586 bytes

In [15]:
import pandas as pd
df=pd.read_csv("irisDataset.csv")
df.head()                        #Load File

   Val1  Val2  Val3  Val4       Output
0   5.1   3.5   1.4   0.2  Iris-setosa
1   4.9   3.0   1.4   0.2  Iris-setosa
2   4.7   3.2   1.3   0.2  Iris-setosa
3   4.6   3.1   1.5   0.2  Iris-setosa
4   5.0   3.6   1.4   0.2  Iris-setosa

In [32]:
Input=df.drop("Output",axis="columns")
Target=df.drop("Val1",axis="columns")            #Separate input output
Target=Target.drop("Val2",axis="columns")
Target=Target.drop("Val3",axis="columns")
Target=Target.drop("Val4",axis="columns")

In [33]:
Input

     Val1  Val2  Val3  Val4
0     5.1   3.5   1.4   0.2
1     4.9   3.0   1.4   0.2
2     4.7   3.2   1.3   0.2
3     4.6   3.1   1.5   0.2
4     5.0   3.6   1.4   0.2
..    ...   ...   ...   ...
145   6.7   3.0   5.2   2.3
146   6.3   2.5   5.0   1.9
147   6.5   3.0   5.2   2.0
148   6.2   3.4   5.4   2.3
149   5.9   3.0   5.1   1.8

[150 rows x 4 columns]

In [34]:
Target

             Output
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 1 columns]

In [35]:
from sklearn.preprocessing import LabelEncoder

In [36]:
le_gender=LabelEncoder()

In [38]:
Target["Output"]=le_gender.fit_transform(Target["Output"])    #Label encode 
Target.head()

   Output
0       0
1       0
2       0
3       0
4       0

In [39]:
from sklearn.model_selection import train_test_split

In [40]:
final_train,final_test,target_train,target_test=train_test_split(Input,Target,test_size=0.2) #Train test split

In [41]:
final_train

     Val1  Val2  Val3  Val4
146   6.3   2.5   5.0   1.9
71    6.1   2.8   4.0   1.3
14    5.8   4.0   1.2   0.2
25    5.0   3.0   1.6   0.2
26    5.0   3.4   1.6   0.4
..    ...   ...   ...   ...
105   7.6   3.0   6.6   2.1
62    6.0   2.2   4.0   1.0
130   7.4   2.8   6.1   1.9
72    6.3   2.5   4.9   1.5
78    6.0   2.9   4.5   1.5

[120 rows x 4 columns]

In [43]:
final_test

     Val1  Val2  Val3  Val4
18    5.7   3.8   1.7   0.3
148   6.2   3.4   5.4   2.3
3     4.6   3.1   1.5   0.2
87    6.3   2.3   4.4   1.3
127   6.1   3.0   4.9   1.8
13    4.3   3.0   1.1   0.1
31    5.4   3.4   1.5   0.4
27    5.2   3.5   1.5   0.2
85    6.0   3.4   4.5   1.6
102   7.1   3.0   5.9   2.1
66    5.6   3.0   4.5   1.5
6     4.6   3.4   1.4   0.3
140   6.7   3.1   5.6   2.4
39    5.1   3.4   1.5   0.2
138   6.0   3.0   4.8   1.8
60    5.0   2.0   3.5   1.0
33    5.5   4.2   1.4   0.2
128   6.4   2.8   5.6   2.1
144   6.7   3.3   5.7   2.5
98    5.1   2.5   3.0   1.1
11    4.8   3.4   1.6   0.2
41    4.5   2.3   1.3   0.3
17    5.1   3.5   1.4   0.3
91    6.1   3.0   4.6   1.4
40    5.0   3.5   1.3   0.3
132   6.4   2.8   5.6   2.2
56    6.3   3.3   4.7   1.6
113   5.7   2.5   5.0   2.0
125   7.2   3.2   6.0   1.8
5     5.4   3.9   1.7   0.4

In [64]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [65]:
#Adding input layer and 1st hidden layer
classifier=Sequential()
#Create input layer
classifier.add(Dense(4,input_shape=(4,),activation="relu"))
#Add 1st hidden layer
classifier.add(Dense(27,activation='relu'))          #Create model
#Add 2nd hidden layer
classifier.add(Dense(9,activation='relu'))
#Add output layer
classifier.add(Dense(1,activation='sigmoid'))

In [66]:
classifier.compile(optimizer=keras.optimizers.SGD(learning_rate=0.1),loss='categorical_crossentropy',metrics=['accuracy'])

In [67]:
classifier.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_12 (Dense)             (None, 4)                 20
_________________________________________________________________
dense_13 (Dense)             (None, 27)                135
_________________________________________________________________
dense_14 (Dense)             (None, 9)                 252
_________________________________________________________________
dense_15 (Dense)             (None, 1)                 10
=================================================================
Total params: 417
Trainable params: 417
Non-trainable params: 0
_________________________________________________________________

In [68]:
classifier.fit(final_train,target_train,batch_size=50,epochs=150)

Epoch 1/150
3/3 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.3008
Epoch 2/150
3/3 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.3417
Epoch 3/150
3/3 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.3742
Epoch 4/150
3/3 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.3317
Epoch 5/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.4083
Epoch 6/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.2817
Epoch 7/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3167
Epoch 8/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3292
Epoch 9/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3042
Epoch 10/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3517
Epoch 11/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.2992
Epoch 12/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3242
Epoch 13/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.2817
Epoch 14/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.2867
Epoch 15/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3217
Epoch 16/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3142
Epoch 17/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.2992
Epoch 18/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3142
Epoch 19/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3367
Epoch 20/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3117
Epoch 21/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3117
Epoch 22/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3192
Epoch 23/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3142
Epoch 24/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.2892
Epoch 25/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.2842
Epoch 26/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3067
Epoch 27/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3217
Epoch 28/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3117
Epoch 29/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3167
Epoch 30/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.2867
Epoch 31/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3117
Epoch 32/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3067
Epoch 33/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3017
Epoch 34/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.2942
Epoch 35/150
3/3 [==============================] - 0s 4ms/step - loss: nan - accuracy: 0.3167
Epoch 36/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3017
Epoch 37/150
3/3 [==============================] - 0s 4ms/step - loss: nan - accuracy: 0.3192
Epoch 38/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3317
Epoch 39/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.2967
Epoch 40/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.2967
Epoch 41/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3017
Epoch 42/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3042
Epoch 43/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3142
Epoch 44/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3242
Epoch 45/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3067
Epoch 46/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3042
Epoch 47/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.2967
Epoch 48/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3017
Epoch 49/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3167
Epoch 50/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3117
Epoch 51/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3067
Epoch 52/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3042
Epoch 53/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3267
Epoch 54/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3067
Epoch 55/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3192
Epoch 56/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3242
Epoch 57/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3242
Epoch 58/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3392
Epoch 59/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.2942
Epoch 60/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3342
Epoch 61/150
3/3 [==============================] - 0s 5ms/step - loss: nan - accuracy: 0.2942
Epoch 62/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3067
Epoch 63/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.2867
Epoch 64/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3292
Epoch 65/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3092
Epoch 66/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3017
Epoch 67/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3167
Epoch 68/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3342
Epoch 69/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3092
Epoch 70/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.2967
Epoch 71/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3117
Epoch 72/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.2667
Epoch 73/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.2967
Epoch 74/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.2917
Epoch 75/150
3/3 [==============================] - 0s 4ms/step - loss: nan - accuracy: 0.3267
Epoch 76/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3217
Epoch 77/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3167
Epoch 78/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3217
Epoch 79/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3092
Epoch 80/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3192
Epoch 81/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.2942
Epoch 82/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3117
Epoch 83/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.2767
Epoch 84/150
3/3 [==============================] - 0s 4ms/step - loss: nan - accuracy: 0.3042
Epoch 85/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.2967
Epoch 86/150
3/3 [==============================] - 0s 5ms/step - loss: nan - accuracy: 0.3192
Epoch 87/150
3/3 [==============================] - 0s 4ms/step - loss: nan - accuracy: 0.3192
Epoch 88/150
3/3 [==============================] - 0s 4ms/step - loss: nan - accuracy: 0.2992
Epoch 89/150
3/3 [==============================] - 0s 4ms/step - loss: nan - accuracy: 0.3142
Epoch 90/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3042
Epoch 91/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.2942
Epoch 92/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3017
Epoch 93/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3042
Epoch 94/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3117
Epoch 95/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3092
Epoch 96/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3267
Epoch 97/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.2942
Epoch 98/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3142
Epoch 99/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3092
Epoch 100/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3167
Epoch 101/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3317
Epoch 102/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3017
Epoch 103/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.2992
Epoch 104/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.2992
Epoch 105/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3142
Epoch 106/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3167
Epoch 107/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3217
Epoch 108/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3142
Epoch 109/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.2867
Epoch 110/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.2842
Epoch 111/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3417
Epoch 112/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.2917
Epoch 113/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3117
Epoch 114/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3217
Epoch 115/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.2917
Epoch 116/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.2967
Epoch 117/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3267
Epoch 118/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3167
Epoch 119/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3167
Epoch 120/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.2942
Epoch 121/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3142
Epoch 122/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3117
Epoch 123/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3067
Epoch 124/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3092
Epoch 125/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.2992
Epoch 126/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3092
Epoch 127/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3242
Epoch 128/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3167
Epoch 129/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3092
Epoch 130/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.2992
Epoch 131/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3092
Epoch 132/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.2842
Epoch 133/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3267
Epoch 134/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3042
Epoch 135/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3067
Epoch 136/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3067
Epoch 137/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3192
Epoch 138/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3217
Epoch 139/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3317
Epoch 140/150
3/3 [==============================] - 0s 4ms/step - loss: nan - accuracy: 0.2792
Epoch 141/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3317
Epoch 142/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3292
Epoch 143/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.2942
Epoch 144/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.2867
Epoch 145/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3017
Epoch 146/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3242
Epoch 147/150
3/3 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.3092
Epoch 148/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.2842
Epoch 149/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3017
Epoch 150/150
3/3 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.3167

In [69]:
outputs=classifier.predict(final_test)

In [70]:
Output

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])